# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='restaurant.proto',
  package='restaurant',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10restaurant.proto\x12\nrestaurant\">\n\x12ReservationRequest\x12(\n\x07reserva\x18\x01 \x01(\x0b\x32\x17.restaurant.Reservation\"\x1b\n\rReservationID\x12\n\n\x02id\x18\x01 \x01(\x05\"\x81\x02\n\x0eServerResponse\x12)\n\x06res_id\x18\x01 \x01(\x0b\x32\x19.restaurant.ReservationID\x12\x35\n\x08response\x18\x02 \x01(\x0e\x32#.restaurant.ServerResponse.Response\x12+\n\nmy_reserva\x18\x03 \x01(\x0b\x32\x17.restaurant.Reservation\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12-\n\x0creserve_list\x18\x05 \x03(\x0b\x32\x17.restaurant.Reservation\"\x1c\n\x08Response\x12\x07\n\x03\x41\x43K\x10\x00\x12\x07\n\x03\x45RR\x10\x01\"\t\n\x07ListReq\"\x97\x01\n\x0bReservation\x12)\n\x06res_id\x18\x01 \x01(\x0b\x32\x19.restaurant.ReservationID\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x0e\n\x06\x64iners\x18\x04 \x01(\x05\x12\x13\n\x0b\x63lient_name\x18\x05 \x01(\t\x12\x1c\n\x14\x63ontact_phone_number\x18\x06 \x01(\t2\x95\x02\n\nRestaurant\x12G\n\x07request\x12\x1e.restaurant.ReservationRequest\x1a\x1a.restaurant.ServerResponse\"\x00\x12@\n\x05\x63heck\x12\x19.restaurant.ReservationID\x1a\x1a.restaurant.ServerResponse\"\x00\x12\x41\n\x06\x63\x61ncel\x12\x19.restaurant.ReservationID\x1a\x1a.restaurant.ServerResponse\"\x00\x12\x39\n\x04list\x12\x13.restaurant.ListReq\x1a\x1a.restaurant.ServerResponse\"\x00\x62\x06proto3'
)



_SERVERRESPONSE_RESPONSE = _descriptor.EnumDescriptor(
  name='Response',
  full_name='restaurant.ServerResponse.Response',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ACK', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ERR', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=355,
  serialized_end=383,
)
_sym_db.RegisterEnumDescriptor(_SERVERRESPONSE_RESPONSE)


_RESERVATIONREQUEST = _descriptor.Descriptor(
  name='ReservationRequest',
  full_name='restaurant.ReservationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reserva', full_name='restaurant.ReservationRequest.reserva', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=94,
)


_RESERVATIONID = _descriptor.Descriptor(
  name='ReservationID',
  full_name='restaurant.ReservationID',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='restaurant.ReservationID.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=96,
  serialized_end=123,
)


_SERVERRESPONSE = _descriptor.Descriptor(
  name='ServerResponse',
  full_name='restaurant.ServerResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res_id', full_name='restaurant.ServerResponse.res_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='response', full_name='restaurant.ServerResponse.response', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='my_reserva', full_name='restaurant.ServerResponse.my_reserva', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='restaurant.ServerResponse.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reserve_list', full_name='restaurant.ServerResponse.reserve_list', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SERVERRESPONSE_RESPONSE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=383,
)


_LISTREQ = _descriptor.Descriptor(
  name='ListReq',
  full_name='restaurant.ListReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=394,
)


_RESERVATION = _descriptor.Descriptor(
  name='Reservation',
  full_name='restaurant.Reservation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='res_id', full_name='restaurant.Reservation.res_id', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='date', full_name='restaurant.Reservation.date', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time', full_name='restaurant.Reservation.time', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='diners', full_name='restaurant.Reservation.diners', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='client_name', full_name='restaurant.Reservation.client_name', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='contact_phone_number', full_name='restaurant.Reservation.contact_phone_number', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=548,
)

_RESERVATIONREQUEST.fields_by_name['reserva'].message_type = _RESERVATION
_SERVERRESPONSE.fields_by_name['res_id'].message_type = _RESERVATIONID
_SERVERRESPONSE.fields_by_name['response'].enum_type = _SERVERRESPONSE_RESPONSE
_SERVERRESPONSE.fields_by_name['my_reserva'].message_type = _RESERVATION
_SERVERRESPONSE.fields_by_name['reserve_list'].message_type = _RESERVATION
_SERVERRESPONSE_RESPONSE.containing_type = _SERVERRESPONSE
_RESERVATION.fields_by_name['res_id'].message_type = _RESERVATIONID
DESCRIPTOR.message_types_by_name['ReservationRequest'] = _RESERVATIONREQUEST
DESCRIPTOR.message_types_by_name['ReservationID'] = _RESERVATIONID
DESCRIPTOR.message_types_by_name['ServerResponse'] = _SERVERRESPONSE
DESCRIPTOR.message_types_by_name['ListReq'] = _LISTREQ
DESCRIPTOR.message_types_by_name['Reservation'] = _RESERVATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReservationRequest = _reflection.GeneratedProtocolMessageType('ReservationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATIONREQUEST,
  '__module__' : 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:restaurant.ReservationRequest)
  })
_sym_db.RegisterMessage(ReservationRequest)

ReservationID = _reflection.GeneratedProtocolMessageType('ReservationID', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATIONID,
  '__module__' : 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:restaurant.ReservationID)
  })
_sym_db.RegisterMessage(ReservationID)

ServerResponse = _reflection.GeneratedProtocolMessageType('ServerResponse', (_message.Message,), {
  'DESCRIPTOR' : _SERVERRESPONSE,
  '__module__' : 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:restaurant.ServerResponse)
  })
_sym_db.RegisterMessage(ServerResponse)

ListReq = _reflection.GeneratedProtocolMessageType('ListReq', (_message.Message,), {
  'DESCRIPTOR' : _LISTREQ,
  '__module__' : 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:restaurant.ListReq)
  })
_sym_db.RegisterMessage(ListReq)

Reservation = _reflection.GeneratedProtocolMessageType('Reservation', (_message.Message,), {
  'DESCRIPTOR' : _RESERVATION,
  '__module__' : 'restaurant_pb2'
  # @@protoc_insertion_point(class_scope:restaurant.Reservation)
  })
_sym_db.RegisterMessage(Reservation)



_RESTAURANT = _descriptor.ServiceDescriptor(
  name='Restaurant',
  full_name='restaurant.Restaurant',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=551,
  serialized_end=828,
  methods=[
  _descriptor.MethodDescriptor(
    name='request',
    full_name='restaurant.Restaurant.request',
    index=0,
    containing_service=None,
    input_type=_RESERVATIONREQUEST,
    output_type=_SERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='check',
    full_name='restaurant.Restaurant.check',
    index=1,
    containing_service=None,
    input_type=_RESERVATIONID,
    output_type=_SERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='cancel',
    full_name='restaurant.Restaurant.cancel',
    index=2,
    containing_service=None,
    input_type=_RESERVATIONID,
    output_type=_SERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='list',
    full_name='restaurant.Restaurant.list',
    index=3,
    containing_service=None,
    input_type=_LISTREQ,
    output_type=_SERVERRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESTAURANT)

DESCRIPTOR.services_by_name['Restaurant'] = _RESTAURANT

# @@protoc_insertion_point(module_scope)
