# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restaurant.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10restaurant.proto\x12\nrestaurant\">\n\x12ReservationRequest\x12(\n\x07reserva\x18\x01 \x01(\x0b\x32\x17.restaurant.Reservation\"#\n\rReservationID\x12\x12\n\nreserve_id\x18\x01 \x01(\x05\"\x81\x02\n\x0eServerResponse\x12)\n\x06res_id\x18\x01 \x01(\x0b\x32\x19.restaurant.ReservationID\x12\x35\n\x08response\x18\x02 \x01(\x0e\x32#.restaurant.ServerResponse.Response\x12+\n\nmy_reserva\x18\x03 \x01(\x0b\x32\x17.restaurant.Reservation\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12-\n\x0creserve_list\x18\x05 \x03(\x0b\x32\x17.restaurant.Reservation\"\x1c\n\x08Response\x12\x07\n\x03\x41\x43K\x10\x00\x12\x07\n\x03\x45RR\x10\x01\"\t\n\x07ListReq\"\x97\x01\n\x0bReservation\x12)\n\x06res_id\x18\x01 \x01(\x0b\x32\x19.restaurant.ReservationID\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\t\x12\x0c\n\x04time\x18\x03 \x01(\t\x12\x0e\n\x06\x64iners\x18\x04 \x01(\x05\x12\x13\n\x0b\x63lient_name\x18\x05 \x01(\t\x12\x1c\n\x14\x63ontact_phone_number\x18\x06 \x01(\t2\x95\x02\n\nRestaurant\x12G\n\x07request\x12\x1e.restaurant.ReservationRequest\x1a\x1a.restaurant.ServerResponse\"\x00\x12@\n\x05\x63heck\x12\x19.restaurant.ReservationID\x1a\x1a.restaurant.ServerResponse\"\x00\x12\x41\n\x06\x63\x61ncel\x12\x19.restaurant.ReservationID\x1a\x1a.restaurant.ServerResponse\"\x00\x12\x39\n\x04list\x12\x13.restaurant.ListReq\x1a\x1a.restaurant.ServerResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'restaurant_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_RESERVATIONREQUEST']._serialized_start=32
  _globals['_RESERVATIONREQUEST']._serialized_end=94
  _globals['_RESERVATIONID']._serialized_start=96
  _globals['_RESERVATIONID']._serialized_end=131
  _globals['_SERVERRESPONSE']._serialized_start=134
  _globals['_SERVERRESPONSE']._serialized_end=391
  _globals['_SERVERRESPONSE_RESPONSE']._serialized_start=363
  _globals['_SERVERRESPONSE_RESPONSE']._serialized_end=391
  _globals['_LISTREQ']._serialized_start=393
  _globals['_LISTREQ']._serialized_end=402
  _globals['_RESERVATION']._serialized_start=405
  _globals['_RESERVATION']._serialized_end=556
  _globals['_RESTAURANT']._serialized_start=559
  _globals['_RESTAURANT']._serialized_end=836
# @@protoc_insertion_point(module_scope)
